import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import About from "../components/About/About";
import Products from "../components/Products/Products";
import Testimonials from "@/components/Testimonials/Testimonials";
import Contact from "@/components/Contact/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teach Mate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://teachmate.imgix.net/favicon-16x16.png" />
      </Head>
      <main>
        <Hero />
        <About />
        <Products />
        <Testimonials />
        <Contact />
      </main>
    </>
  );
}
